---
- block:
  - name: import gpg key
    rpm_key:
      key: https://github.com/sacloud/usacloud/releases/latest/repos/GPG-KEY-usacloud
  - name: add repository
    yum_repository:
      name: usacloud
      description: usacloud
      baseurl: https://github.com/sacloud/usacloud/releases/latest/repos/centos/$basearch
      gpgcheck: true
      file: usacloud
  - name: install usacloud
    yum:
      name: usacloud
  become: true
  when: ansible_os_family == 'RedHat'
- block:
  - name: install apt-transport-https
    apt:
      name: apt-transport-https
  - name: import gpg key
    apt_key:
      url: https://releases.usacloud.jp/usacloud/repos/GPG-KEY-usacloud
  - name: add repository
    apt_repository:
      repo: deb https://github.com/sacloud/usacloud/releases/latest/repos/debian /
      filename: usacloud
  - name: install usacloud
    apt:
      name: usacloud
      update_cache: true
  become: true
  when: ansible_os_family == 'Debian'
- block:
    - name: add repository
      homebrew_tap:
        name: sacloud/homebrew-usacloud
    - name: install usacloud
      homebrew:
        name: usacloud
  become: false
  when: ansible_os_family == 'Darwin'
- name: install usacloud
  win_chocolatey:
    name: usacloud
  when: ansible_os_family == 'Windows'
